version: '2'
services:
    fin-app:
        image: fin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fin-postgresql:5432/fin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    fin-postgresql:
        extends:
            file: postgresql.yml
            service: fin-postgresql
